### PR TITLE
Packaging

### PR DESCRIPTION
**Pull request by jpmorgan98**
Trying to figure out the import functions when python directory not named `harmonize` as is nominal in pip

### CODE REVIEW

**Comment by braxtoncuneo** [comment]
If the directory name is a big hurdle, we can change it to fit. I was mainly looking to replicate the organization of mainstream C++ libraries, but - since we're in a point of transition anyway - we can restructure it to make Python deployment easier.

We could rename "include" into "harmonize" and move the Python bindings (or at least the root module of the bindings) next to "harmonize.h". We could also fold "src" in as "harmonize/cpp", with any additional Python code in "harmonize/python" subdirectory.

If you have other ideas for how we could structure this, I'm open to alternatives.

**Comment by jpmorgan98** [comment]
Nah it should be fine, I think I found a way to do it in a [pyproject def](https://hatch.pypa.io/1.9/config/build/#packages). Only problem is it doesn't currently work. I can install 
```
harmonize by 
cd Hamonize
pip install -e .
```
It will show up in `pip list` but will then result in an import error when in python. Also if you import harmonize on a non cuda enabled machine it will initialize cuda and what not and fail if you are not on a CUDA based system

**Comment by braxtoncuneo** [comment]
I believe this new commit should fix the import problem.

I ran the following in a fresh conda environment:
```
cd harmonize
pip install -e .
cd examples/python/collaz
python3 collaz.py
```
and it appears to work.

**Comment by jpmorgan98** [comment]
Ok This should be ready for the merge! Just review everything I've done approve it then I will get the PiPy stuff configured

**Comment by braxtoncuneo** [comment]
Sounds good. I'll test this on lassen as final confirmation.

**Comment by jpmorgan98** [comment]
Can we run harmonize in CPU mode? Asking to see if we can get any testing via github actions

**Comment by jpmorgan98** [comment]
#2

**Comment by braxtoncuneo** [comment]
Running in CPU mode would require gluing together the async functions to replicate what the gpu-side runtime is doing. Integrating host-side async into harmonize could be done, but it would take some time to do.

**Comment by braxtoncuneo** [comment]
As for running on lassen, it has been a bit of a challenge. I do now have a working build, but it requires a completely different setup.

Assuming this is in a fresh conda environment:
```
conda install -c conda-forge gxx
conda install -c conda-forge python=3.11
conda install numba
conda install numpy
conda upgrade numba
```

This isn't ideal, but at least some of these steps may be necessary. Lassen doesn't have up-to-date gcc/g++, which numpy relies upon. Lassen doesn't have up-to-date llvm, and llvmlite (and numba by extension) is a stickler about having *exactly* the right llvm version. I have tried to swap out some of these conda steps with analogous pip installs, but that causes the environment to break for some reason (i.e. calling `conda list` results in conda crashing).

In case you find it useful, here is a full listing of the conda environment:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
binutils_impl_linux-ppc64le 2.39                 h6c0ba3f_0    conda-forge
blas                      1.0                    openblas  
bzip2                     1.0.8                h4e0d66e_4    conda-forge
ca-certificates           2023.08.22           h6ffa863_0  
gcc                       12.2.0              h5da947c_11    conda-forge
gcc_impl_linux-ppc64le    12.2.0              h3a350b8_19    conda-forge
gxx_impl_linux-ppc64le    12.2.0              h3a350b8_19    conda-forge
kernel-headers_linux-ppc64le 3.10.0              h1da2f99_10  
ld_impl_linux-ppc64le     2.39                 hb4302b2_0    conda-forge
libffi                    3.4.2                h4e0d66e_5    conda-forge
libgcc-devel_linux-ppc64le 12.2.0              hccfcbdc_19    conda-forge
libgcc-ng                 12.2.0              hbc1322c_19    conda-forge
libgfortran-ng            11.2.0               hb3889a9_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   12.2.0              hbc1322c_19    conda-forge
libllvm10                 10.0.1               h9b6764f_5  
libllvm11                 11.1.0               h621ed2f_6  
libnsl                    2.0.0                h4e0d66e_0    conda-forge
libopenblas               0.3.21               hd3ce00b_0  
libsanitizer              12.2.0              h99369c6_19    conda-forge
libstdcxx-devel_linux-ppc64le 12.2.0              hccfcbdc_19    conda-forge
libstdcxx-ng              12.2.0              h99369c6_19    conda-forge
libuuid                   2.32.1            h4e0d66e_1000    conda-forge
llvmlite                  0.38.0           py39h5f94dde_0  
ncurses                   6.4                  h4a02239_0  
numba                     0.55.1           py39haab0e66_0  
numpy                     1.21.5           py39h181cc9a_3  
numpy-base                1.21.5           py39h1bde650_3  
openssl                   3.0.12               h140841e_0  
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
python                    3.9.18               h112ed23_0  
readline                  8.1.2                h6828edc_0    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
sqlite                    3.41.2               hf118e41_0  
sysroot_linux-ppc64le     2.17                h302c3fa_10  
tk                        8.6.12               h7e00dab_0  
tzdata                    2022f                h191b570_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.4.2                hf118e41_0  
zlib                      1.2.13               hf118e41_0 
```

Moving forward (assuming we can get the pip packages to install over the conda packages) do you think it would be better to take care of the non-python dependencies, or leave that to the user? If we do plan on taking care of these dependencies, would we bundle them into a wheel to keep using pip, or should harmonize be a conda package?

**Comment by jpmorgan98** [comment]
Ya I think conda is the way to go. Eventually I want to get MC/DC on conda to so this would be a nice test case

**Pull request closed without merging**
